### ISSUE TITLE
Update docu

### ISSUE THREAD

**Issue by papanito** [papanito/ansible-role-diskmounter#2]
The example in the docu is wrong and shall be updated to mach the role name.
Also check for correctness and completeness of docu.

**Comment by 4F2E4A2E** [comment]
Hey there, thank you for this repo, but just a quick one: can you pls provide a working example?

**Comment by papanito** [comment]
```
---
- ​hosts​: ​localhost​
  ​vars​:
    ​remote_user​: ​"​{{ localuser }}​"​
    ​user​: ​"​{{ localuser }}​"​
    ​smb_shares​:
      ​demo​: ​#​ share which uses no credentails​
        ​path​: ​/mnt/demo​
        ​src​: ​//192.168.0.1/demo​
        ​options​: ​file_mode=0777,dir_mode=0777,rw,uid=1000,gid=1000,sec=none,vers=1.0,nounix​
      ​freenas​: ​#​ share with credentials​
        ​path​: ​/mnt/freenas​
        ​src​: ​//192.168.0.1/media​
        ​options​: ​file_mode=0777,dir_mode=0777,rw,uid=1000,gid=1000,sec=none,vers=1.0,nounix​
        ​credentials​:
          ​username​: ​usera​
          ​passsword​: ​MySmbPassword​
          ​domain​: ​domain​
  ​roles​:
    - ​papanito.diskmounter
```

**Comment by papanito** [comment]
@4F2E4A2E hope the docu is no more clear. Role name is [`papanito.diskmounter`](https://galaxy.ansible.com/papanito/diskmounter)

**Comment by 4F2E4A2E** [comment]
Thank you so much, it makes sense now. I will try it out on a centos8 and give feedback 👍

**Comment by 4F2E4A2E** [comment]
Despite the ZWSP [1] and typo `pas_s_sword `

(intellij)
![image](https://user-images.githubusercontent.com/64590/91667071-33382180-eb02-11ea-9815-76dc26520758.png)
(vscode)
![image](https://user-images.githubusercontent.com/64590/91667091-4a770f00-eb02-11ea-853a-810fca6d2180.png)

and the misplaced variable
![image](https://user-images.githubusercontent.com/64590/91667526-8495e000-eb05-11ea-9bcf-fbbee910716b.png)

It actually did work, thank you.

Here is a working example mounting a windows 10 share on a centos8 using ansible 2.9+:  

```
- name: Here is a working example mounting a windows 10 share on a centos8 using ansible 2.9+
  hosts: localhost
  vars:
    remote_user: root
    smb_shares:
      .example:
        path: /data/share-example-mount
        src: //192.168.1.102/share-example
        options: uid=1000,gid=1000,rw,nounix,iocharset=utf8,file_mode=0777,dir_mode=0777
        credentials:
          username: developer
          password: developer
          domain: workgroup
  roles:
    - role: papanito.diskmounter

``` 

1: https://stackoverflow1.com/a/63661024/543426
